name: Deploy All Images

on:
  workflow_dispatch:
    inputs:
      # environment:
      #   description: Environment to deploy to
      #   type: choice
      #   options: [DEV]
      matrix_json:
        description: JSON string containing services matrix info
        type: string

# env:
  # Name of JSON secret should be SERVICES_MATRIX_DEV, etc..
  # There should be a secret of the same name containing json matching ./dev.env.json.example
  # MATRIX_JSON: ${{ secrets[format('SERVICES_MATRIX_{0}', github.event.inputs.environment)] }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        # include: ${{ fromJson(env.MATRIX_JSON) }}
        include: ${{ fromJson(inputs.matrix_json) }}

    # Eventually change this to use {owner}/{repo}/.github/workflows/{filename}@{ref} format
    # since one main action will run many reusable workflows
    uses: ./.github/workflows/publish-image.yml
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ecr_repository: ${{ matrix.ecr_repository }}
      task_definition_arn: ${{ matrix.task_definition_arn }}
      container: ${{ matrix.container }}
      cluster: ${{ matrix.cluster }}
      service: ${{ matrix.service }}
